# leaving the dict work here so it lands in the coming test framework

### this is the original PoC dict, categorizing the user_request and providing test/demo questions

In [1]:

inputs_dict = {
     'verify_resort': {
        'user_request': "is there a resort called Orbit One?"
    },
    'verify_resort_plus': {
        'user_request': "What is the club availability at Grand Vacations at Tuscany Village?"
    },
     'parse_name_filter_dataset': {
        'user_request': "how many 2 bedrooms are available in September at Desert Retreat?"
    },
    'property_analysis_hard': {
        'user_request': "How many Dev units are available at Aqua Sol in September?"
    },
    'property_analysis_general_off_name': {
        'user_request': "What's the availability for September 2024 at Tuscany Village?"
    },
    'property_analysis_2_stage_brdm': {
        'user_request': "How many 1-bedroom units are available in November 2024 at Tuscany Village?"
    },
    'visualization_pie_all_data': {
        'user_request': "Create a pie chart of availability by segment for all data."
    },
    'visualization_pie_month_year': {
        'user_request': "Create a pie chart showing availability of different segments for all properties for Nov 2024."
    },
    'visualization_club_heatmap': {
        'user_request': "Create a heatmap showing total club availability by month.  use a depressing colormap."
    },
    'segment_analysis': {
        'user_request': "How is the availability distributed for max booked segment in November 2024 at Flamingo Beach?"
    },
}

In [3]:
import pandas as pd

In [7]:
pd.DataFrame(inputs_dict)

,verify_resort,verify_resort_plus,parse_name_filter_dataset,property_analysis_hard,property_analysis_general_off_name,property_analysis_2_stage_brdm,visualization_pie_all_data,visualization_pie_month_year,visualization_club_heatmap,segment_analysis
user_request,is there a resort called Orbit One?,What is the club availability at Grand Vacatio...,how many 2 bedrooms are available in September...,How many Dev units are available at Aqua Sol i...,What's the availability for September 2024 at ...,How many 1-bedroom units are available in Nove...,Create a pie chart of availability by segment ...,Create a pie chart showing availability of dif...,Create a heatmap showing total club availabili...,How is the availability distributed for max bo...

# New questions and answers plus other useful attributes for testing and regression defense

new set of attributes and explanations:
* test/eval name:  ex. "verify_resort_typo": 
* description: example: "Check if a resort exists with a possible typo.",
* category": "inventory_text", (use case category, ex. inventory, demand prediction, advanced analysis/comparison)
* user_request": "Is Tusckanny Villoge a resort name?",
* expected_answer": like "Did you mean Tuscany Village, a Hilton Grand Vacations Club?",
* difficulty": "easy", (t-shirts size for now)
* exact_response": False, (eval instructions (exact for data pulls to table or data in text)
* is_edge_case": True, (cases designed to test functionality and prove accuracy for tricky questions and reduce unexpected results)
* is_test_case": True, (canon test suite--run for LLM-side of CI/CD or key commits)
* is_graphical": False,(text/table vs. text for eval)
* expected_agent_flow": "A1, A2,"

In [19]:
# imports
import pandas as pd

q_a_dict = {
    "verify_resort_typo": {
        "description": "Check if a resort exists with a possible typo.",
        "category": "inventory_text",
        "user_request": "Is Tusckanny Villoge a resort name?",
        "expected_answer": "Did you mean Tuscany Village, a Hilton Grand Vacations Club?",
        "difficulty": "easy",
        "exact_response": False,
        "is_edge_case": True,
        "is_test_case": True,
        "is_graphical": False,
        # "expected_agent_flow": "A1, A2,"
    },
        "verify_false_resort": {
        "description": "Check if a resort exists with a possible typo.",
        "category": "inventory_text",
        "user_request": "Is El brillante Mañana Resort de Женя a resort name?",
        "expected_answer": "No",
        "difficulty": "medium",
        "exact_response": False,
        "is_edge_case": True,
        "is_test_case": True,
        "is_graphical": False,
        # "expected_agent_flow": "A1, A2,"
    },
    "dev_availability_specific_resort": {
        "description": "Check developer availability for a specific resort and date.",
        "category": "inventory_table",
        "user_request": "Give me the dev availability for November 2024 for VDG.",
        "expected_answer": "Table showing developer segment availability for Vilar Do Golf in November 2024.",
        "difficulty": "hard",
        "exact_response": False,
        "is_edge_case": False,
        "is_test_case": True,
        "is_graphical": True,
        # "expected_agent_flow": "A1, A2,"
    },
    "verify_resort_tuscany": {
        "description": "Check if a resort exists.",
        "category": "inventory_text",
        "user_request": "Is there a resort called Tusciny Vilage?",
        "expected_answer": "Yes, Tuscany Village, a Hilton Grand Vacations Club is a valid resort.",
        "difficulty": "easy",
        "exact_response": True,
        "is_edge_case": False,
        "is_test_case": True,
        "is_graphical": False,
        # "expected_agent_flow": "A1, A2,"
    },
    "availability_check_flamingo": {
        "description": "Check availability for a specific segment and resort.",
        "category": "inventory_table",
        "user_request": "What is the availability for developer units at Flamingo in September 2024?",
        "expected_answer": "Table showing developer segment availability for Flamingo, a Hilton Grand Vacations Club in September 2024.",
        "difficulty": "medium",
        "exact_response": False,
        "is_edge_case": False,
        "is_test_case": True,
        "is_graphical": False,
        # "expected_agent_flow": "A1, A2,"
    },
    "visualization_pie_availability": {
        "description": "Generate a pie chart showing availability by segment for a specific month.",
        "category": "inventory_graph",
        "user_request": "Create a pie chart showing availability of different segments for all properties for November 2024.",
        "expected_answer": "Pie chart displaying segment availability across all properties for November 2024.",
        "difficulty": "hard",
        "exact_response": False,
        "is_edge_case": False,
        "is_test_case": True,
        "is_graphical": True,
        # "expected_agent_flow": "A1, A2,"
    },
    "verify_resort_boulevard": {
        "description": "Check if a resort exists.",
        "category": "inventory_text",
        "user_request": "Is there a resort called The Boulevard?",
        "expected_answer": "Yes, The Boulevard, a Hilton Grand Vacations Club is a valid resort.",
        "difficulty": "easy",
        "exact_response": True,
        "is_edge_case": False,
        "is_test_case": True,
        "is_graphical": False,
        # "expected_agent_flow": "A1, A2,"
    },
    "availability_check_parc_soleil": {
        "description": "Check availability for a specific segment and resort.",
        "category": "inventory_value",
        "user_request": "What is the availability for club units at Parc Soleil in December 8, 2024?",
        "expected_answer": "Table showing club segment availability for Parc Soleil, a Hilton Grand Vacations Club in December 2024.",
        "difficulty": "medium",
        "exact_response": True,
        "is_edge_case": False,
        "is_test_case": True,
        "is_graphical": False,
        # "expected_agent_flow": "A1, A2,"
    },
    "verify_resort_grand_waikikian": {
        "description": "Check if a resort exists.",
        "category": "inventory_text",
        "user_request": "Is there a resort called Grand Waikikian?",
        "expected_answer": "Yes, Grand Waikikian, a Hilton Grand Vacations Club is a valid resort.",
        "difficulty": "easy",
        "exact_response": False,
        "is_edge_case": False,
        "is_test_case": True,
        "is_graphical": False,
        # "expected_agent_flow": "A1, A2,"
    },
    "availability_check_maui_bay_villas": {
        "description": "Check availability for a specific segment and resort.",
        "category": "inventory_table",
        "user_request": "What is the availability for club units at Maui Bay Villas in October 2024?",
        "expected_answer": "Table showing club segment availability for Maui Bay Villas, a Hilton Grand Vacations Club in October 2024.",
        "difficulty": "medium",
        "exact_response": False,
        "is_edge_case": False,
        "is_test_case": True,
        "is_graphical": False,
        # "expected_agent_flow": "A1, A2,"
    },
     "availability_check_maui_bay_villas": {
        "description": "Check availability for a specific segment and resort.",
        "category": "inventory_graph",
        "user_request": "Make a chart of the availability for club units at Maui Bay Villas in October 2024?",
        "expected_answer": "Graph showing club segment availability for Maui Bay Villas, a Hilton Grand Vacations Club in October 2024.",
        "difficulty": "hard",
        "exact_response": False,
        "is_edge_case": False,
        "is_test_case": True,
        "is_graphical": True,
        # "expected_agent_flow": "A1, A2,"
    }
}

# wrap in df and make more useful

In [21]:
# Convert q_a_dict to a Pandas DataFrame
df = pd.DataFrame.from_dict(q_a_dict, orient='index')


# Function to query based on criteria
def query_tests(category=None, difficulty=None, graphical=None, edge_case=None):
    """Filter test cases based on criteria."""
    filtered_df = df.copy()

    if category:
        filtered_df = filtered_df[filtered_df["category"] == category]
    if difficulty:
        filtered_df = filtered_df[filtered_df["difficulty"] == difficulty]
    if graphical is not None:
        filtered_df = filtered_df[filtered_df["is_graphical"] == graphical]
    if edge_case is not None:
        filtered_df = filtered_df[filtered_df["is_edge_case"] == edge_case]

    return filtered_df

In [23]:
query_tests(category=None, difficulty=None, graphical=None, edge_case=None)

,description,category,user_request,expected_answer,difficulty,exact_response,is_edge_case,is_test_case,is_graphical
verify_resort_typo,Check if a resort exists with a possible typo.,inventory_text,Is Tusckanny Villoge a resort name?,"Did you mean Tuscany Village, a Hilton Grand V...",easy,False,True,True,False
verify_false_resort,Check if a resort exists with a possible typo.,inventory_text,Is El brillante Mañana Resort de Женя a resort...,No,medium,False,True,True,False
dev_availability_specific_resort,Check developer availability for a specific re...,inventory_table,Give me the dev availability for November 2024...,Table showing developer segment availability f...,hard,False,False,True,True
verify_resort_tuscany,Check if a resort exists.,inventory_text,Is there a resort called Tusciny Vilage?,"Yes, Tuscany Village, a Hilton Grand Vacations...",easy,True,False,True,False
availability_check_flamingo,Check availability for a specific segment and ...,inventory_table,What is the availability for developer units a...,Table showing developer segment availability f...,medium,False,False,True,False
visualization_pie_availability,Generate a pie chart showing availability by s...,inventory_graph,Create a pie chart showing availability of dif...,Pie chart displaying segment availability acro...,hard,False,False,True,True
verify_resort_boulevard,Check if a resort exists.,inventory_text,Is there a resort called The Boulevard?,"Yes, The Boulevard, a Hilton Grand Vacations C...",easy,True,False,True,False
availability_check_parc_soleil,Check availability for a specific segment and ...,inventory_value,What is the availability for club units at Par...,Table showing club segment availability for Pa...,medium,True,False,True,False
verify_resort_grand_waikikian,Check if a resort exists.,inventory_text,Is there a resort called Grand Waikikian?,"Yes, Grand Waikikian, a Hilton Grand Vacations...",easy,False,False,True,False
availability_check_maui_bay_villas,Check availability for a specific segment and ...,inventory_graph,Make a chart of the availability for club unit...,Graph showing club segment availability for Ma...,hard,False,False,True,True

In [25]:
# generate list of questions for testing
test_questions = df[df["is_test_case"] == True]["user_request"].tolist()

In [27]:
test_questions

['Is Tusckanny Villoge a resort name?',
 'Is El brillante Mañana Resort de Женя a resort name?',
 'Give me the dev availability for November 2024 for VDG.',
 'Is there a resort called Tusciny Vilage?',
 'What is the availability for developer units at Flamingo in September 2024?',
 'Create a pie chart showing availability of different segments for all properties for November 2024.',
 'Is there a resort called The Boulevard?',
 'What is the availability for club units at Parc Soleil in December 8, 2024?',
 'Is there a resort called Grand Waikikian?',
 'Make a chart of the availability for club units at Maui Bay Villas in October 2024?']

In [ ]:
# using pretty frames (skip)

In [12]:
# Convert q_a_dict to a Pandas DataFrame
df = pd.DataFrame.from_dict(q_a_dict, orient='index')

# Display the entire DataFrame
import ace_tools as tools
tools.display_dataframe_to_user(name="Q&A DataFrame", dataframe=df)

# Function to query based on criteria
def query_tests(category=None, difficulty=None, graphical=None, edge_case=None):
    """Filter test cases based on criteria."""
    filtered_df = df.copy()

    if category:
        filtered_df = filtered_df[filtered_df["category"] == category]
    if difficulty:
        filtered_df = filtered_df[filtered_df["difficulty"] == difficulty]
    if graphical is not None:
        filtered_df = filtered_df[filtered_df["is_graphical"] == graphical]
    if edge_case is not None:
        filtered_df = filtered_df[filtered_df["is_edge_case"] == edge_case]

    tools.display_dataframe_to_user(name="Filtered Test Cases", dataframe=filtered_df)
    return filtered_df

In [ ]:
query_tests(category=None, difficulty=None, graphical=None, edge_case=None)